apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vmoperator
  namespace: monitoring
spec:
  chart:
    spec:
      version: v0.10.2
  values:
    resources:
      limits:
        cpu: 100m
        memory: 300Mi
      requests:
        cpu: 50m
        memory: 100Mi
