apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: matomo
  namespace: matomo
spec:
  releaseName: matomo
  chart:
    spec:
      chart: matomo
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
        version: "10.0.2"
    interval: 1h
  install:
    createNamespace: true
  upgrade:
    remediation:
      retries: 3
  values:
    service:
      type: ClusterIP
