# For every Pod in the namespace, each container must have a memory request, memory limit, cpu request, and cpu limit.
# The memory request total for all Pods in that namespace must not exceed 1 GiB.
# The memory limit total for all Pods in that namespace must not exceed 2 GiB.
# The CPU request total for all Pods in that namespace must not exceed 1 cpu.
# The CPU limit total for all Pods in that namespace must not exceed 2 cpu.

apiVersion: v1
kind: ResourceQuota
metadata:
  name: common-resource-quota
spec:
  hard:
    persistentvolumeclaims: "2"
    requests.storage: "5Gi" # cumulative capacity of PVCs
    pods: "5"
    services.loadbalancers: "0" # we have only one service of type LB in cluster for ingress
    services.nodeports: "0"
    # requests.cpu: "1"
    # requests.memory: 1Gi
    # limits.cpu: "2"
    # limits.memory: 2Gi
