apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - grafana-dashboardDatasources.yaml
  - grafana-dashboardDefinitions.yaml
  - grafana-dashboardSources.yaml
  - grafana-deployment.yaml
  - grafana-prometheusRule.yaml
  - grafana-service.yaml
  - grafana-serviceAccount.yaml
  - grafana-serviceMonitor.yaml
  - grafana-storage-pvc.yaml
  - grafana-ingress.yaml
