apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kai-scheduler
  namespace: kai-scheduler
spec:
  interval: 1h
  install:
    createNamespace: true
    crds: Create
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: oci://ghcr.io/nvidia/kai-scheduler/kai-scheduler
      version: v0.7.7
      reconcileStrategy: ChartVersion
  values:
    global:
      gpuSharing: true
      installCRDs: true
