apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: paris-postgres-exporter
  namespace: monitoring
spec:
  releaseName: paris-postgres-exporter
  chart:
    spec:
      chart: prometheus-postgres-exporter
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      version: 3.0.3
  interval: 1h
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/prometheus-community/helm-charts/blob/prometheus-postgres-exporter-3.0.3/charts/prometheus-postgres-exporter/values.yaml
  values:
    service:
      port: 9187
    serviceMonitor:
      enabled: true
      namespace: monitoring
      interval: 30s
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
    rbac:
      create: false
      pspEnabled: false
    serviceAccount:
      create: false
    config:
      datasource:
        host: paris.k8s-01.kontur.io.
        user: postgres_exporter
        database: postgres
        passwordSecret:
          name: paris-postgres-exporter
          key: data_source_password
        sslmode: require
      logLevel: "info"
      logFormat: "logfmt"
