apiVersion: v1
kind: ResourceQuota
metadata:
  name: common-resource-quota
spec:
  hard:
    persistentvolumeclaims: "10"
    requests.storage: "50Gi" # cumulative capacity of PVCs
    pods: "50"
    services.loadbalancers: "0" # we have only one service of type LB in cluster for ingress
    services.nodeports: "0"
