apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/podinfo
#  - ../../base/vmcluster
patchesStrategicMerge:
  - podinfo/release.yaml
#  - vmcluster/vmcluster-crd.yaml
