apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/vmcluster
  - ../../base/flux
  - ../../base/cert-manager
patchesStrategicMerge:
  - vmcluster/vmcluster-crd.yaml
  - flux/alerts.yaml
  - cert-manager/cluster_issuer_letsencrypt_prod.yaml
  - cert-manager/cluster_issuer_letsencrypt_stage.yaml
  - cert-manager/release.yaml
