apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/vmcluster
  - ../../base/flux
  - ../../base/cert-manager
  - ../../base/kube-prometheus/_custom_rules
  - ../../base/kube-prometheus/alertmanager
  - ../../base/kube-prometheus/blackbox-exporter
  - ../../base/kube-prometheus/grafana
  - ../../base/kube-prometheus/kube-state-metrics
  - ../../base/kube-prometheus/kubernetes-servicemonitors
  - ../../base/kube-prometheus/node-exporter
  - ../../base/kube-prometheus/prometheus
  - ../../base/kube-prometheus/prometheus-adapter
  - ../../base/kube-prometheus/victoriametrics  
patchesStrategicMerge:
  - vmcluster/vmcluster-crd.yaml
  - flux/alerts.yaml
  - cert-manager/cluster_issuer_letsencrypt_prod.yaml
  - cert-manager/cluster_issuer_letsencrypt_stage.yaml
  - cert-manager/release.yaml
  - prometheus/prometheus-prometheus.yaml
