apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/vmcluster
  - ../../base/flux
  - ../../base/weave-gitops
  - ../../base/dex
patchesStrategicMerge:
  - vmcluster/vmcluster-crd.yaml
  - flux/alerts.yaml
  - weave-gitops/release.yaml
  - dex/release.yaml
