apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/resource-quota

namespace: sandbox-prytvinsky

patchesJson6902:
  - target:
      kind: ResourceQuota
      name: common-resource-quota
      version: v1
    patch: |-
      - op: replace
        path: /spec/hard/persistentvolumeclaims
        value: "5"
