apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: test-insights-api-db-pg17-postgres-exporter
  namespace: test-insights-api
spec:
  releaseName: test-insights-api-db-pg17-postgres-exporter
  chart:
    spec:
      chart: prometheus-postgres-exporter
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      version: 3.0.3
  interval: 1h
  install:
    remediation:
      retries: 3
  values:
    fullnameOverride: test-insights-api-db-pg17-exporter
    service:
      port: 9187
    serviceMonitor:
      enabled: true
      namespace: test-insights-api
      interval: 60s
      scrapeTimeout: 55s
      labels:
        role: master
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 300m
        memory: 256Mi
    rbac:
      create: true
      pspEnabled: false
    serviceAccount:
      create: true
    config:
      datasource:
        host: db-insights-api-pg17-primary.test-insights-api.svc
        user: insights-api
        database: insights-api
        passwordSecret:
          name: test-insights-api-db-pg17-postgres-exporter
          key: data_source_password
        sslmode: require
      logLevel: "info"
      logFormat: "logfmt"
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: test-insights-api-db-pg17-postgres-exporter-replica
  namespace: monitoring
spec:
  releaseName: test-insights-api-db-pg17-exporter-replica
  chart:
    spec:
      chart: prometheus-postgres-exporter
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      version: 3.0.3
  interval: 1h
  install:
    remediation:
      retries: 3
  values:
    fullnameOverride: test-insights-api-db-pg17-postgres-exporter-replica
    service:
      port: 9187
    serviceMonitor:
      enabled: true
      namespace: test-insights-api
      interval: 60s
      scrapeTimeout: 55s
      labels:
        role: replica
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 300m
        memory: 256Mi
    rbac:
      create: true
      pspEnabled: false
    serviceAccount:
      create: true
      name: test-insights-api-db-pg17-exporter-sa-replica
    config:
      datasource:
        host: db-insights-api-pg17-replicas.test-insights-api.svc
        user: insights-api
        database: insights-api
        passwordSecret:
          name: test-insights-api-db-pg17-postgres-exporter
          key: data_source_password
        sslmode: require
      logLevel: "info"
      logFormat: "logfmt"
