apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: volcano
  namespace: volcano-system
spec:
  releaseName: volcano
  chart:
    spec:
      chart: volcano
      version: 1.12.1
      sourceRef:
        kind: HelmRepository
        name: volcano
        namespace: flux-system
      reconcileStrategy: ChartVersion
  interval: 1h
  install:
    createNamespace: true
    crds: Create
  upgrade:
    crds: CreateReplace
