apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.org/server-snippets: |
      location /api/live/ {
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_set_header Host $http_host;
        proxy_pass http://grafana.monitoring.svc.cluster.local:3000;
      }
  name: grafana02-kontur-io
  namespace: monitoring
spec:
  rules:
  - host: grafana.k8s-02.konturlabs.com
    http:
      paths:
      - backend:
          service:
            name: grafana
            port:
              number: 3000
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - grafana.k8s-02.konturlabs.com
    secretName: grafana-kontur-io-tls
