apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
  labels:
    app.kubernetes.io/name: grafana
    vol: grafana-storage-vol
  name: grafana-storage-pvc
  namespace: monitoring
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
  volumeMode: Filesystem
