apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana02-kontur-io
  namespace: monitoring
spec:
  rules:
    - host: grafana.k8s-02.konturlabs.com
  tls:
    - hosts:
        - grafana.k8s-02.konturlabs.com
      secretName: grafana-k8s-02-konturlabs-com-tls
