apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: pgo-kustomize-installer
  namespace: flux-system
spec:
  gitImplementation: go-git
  ignore: |
    /*
    !/kustomize
    /kustomize/**/.gitignore
    /kustomize/**/.gitattributes
  interval: 1m0s
  ref:
    # branch: main
    #commit: 206cc6aa0aa148133d3147d286f9b3c68b820ffb
  timeout: 60s
  url: 'https://github.com/konturio/postgres-operator-examples'
