apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: pgo-kustomize-installer
  namespace: flux-system
spec:
  ignore: |
    /*
    !/kustomize
    /kustomize/**/.gitignore
    /kustomize/**/.gitattributes
  interval: 1m0s
  ref:
    # branch: main
    commit: 47bcbe6c95e81db2cfecee8f34b1a9389d109338
  timeout: 60s
  url: 'https://github.com/konturio/postgres-operator-examples'
