apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  chart:
    spec:
      chart: ingress-nginx
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: ingress-nginx
      version: 1.8.1
  install:
    crds: Create
  interval: 10m
  suspend: false
  upgrade:
    # Create new CRDs, update (replace) existing ones, but do not delete CRDs which no longer exist in the current helm release.
    crds: CreateReplace
  values:
    controller:
      podAnnotations:
        prometheus.io/scrape: true
        prometheus.io/port: 10254
      config:
        http-snippet: |
          include CORS_01_http.inc.conf;
          include redirect_handling.conf;
        main-snippet: |
          pcre_jit on;
          load_module /usr/lib/nginx/modules/ngx_http_headers_more_filter_module.so;
          load_module /usr/lib/nginx/modules/ngx_http_js_module.so;
        allow-snippet-annotations: true
        enable-access-log-for-default-backend: "true"
        worker-processes: "4"
      # The Ingress Controller processes all the resources that do not have the "ingressClassName" field for all versions of kubernetes.
      ingressClass: ingress-nginx

      image:
        repository: 'nexus.kontur.io:8084/konturdev/ingress-nginx'
        tag: 1.8.0
      ingressClassResource:
        name: ingress-nginx
      metrics:
        serviceMonitor:
          enabled: true
        enabled: true

      # The number of replicas of the Ingress controller deployment.
      replicaCount: 2
      service:
        # The annotations of the Ingress Controller service.
        annotations:
          metallb.universe.tf/address-pool: default
          metallb.universe.tf/allow-shared-ip: SHARED-IP-02
        # The externalTrafficPolicy of the service. The value Local preserves the client source IP.
        externalTrafficPolicy: Cluster
