apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 5m0s
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  chart:
    spec:
      chart: ingress-nginx
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: ingress-nginx
      version: 4.8.2
  install:
    crds: Create
  interval: 10m
  suspend: false
  upgrade:
    # Create new CRDs, update (replace) existing ones, but do not delete CRDs which no longer exist in the current helm release.
    crds: CreateReplace
  values:
    controller:
      podAnnotations:
        prometheus.io/scrape: true
        prometheus.io/port: 10254
      config:
        http-snippet: |
          include /etc/nginx/CORS_01_http.inc.conf;
          map "$host" $dn2021_robots_txt {
            "~*^(?:www\.)?disaster\.ninja$"   "User-agent: *\nAllow: /\n";
            default                           "User-agent: RED\nDisallow:\n\nUser-agent: *\nDisallow: /\n";
          }
        main-snippet: |
          pcre_jit on;
        server-snippet: |
          include /etc/nginx/redirect_handling.conf;
        enable-access-log-for-default-backend: "true"
        worker-processes: "4"
      # The Ingress Controller processes all the resources that do not have the "ingressClassName" field for all versions of kubernetes.
      ingressClass: ingress-nginx

      image:
        repository: 'nexus.kontur.io:8085/konturdev/ingress-nginx'
        tag: 1.8.0
        digest: sha256:be49aa6859d3a789b053396946ccf906000608c973769e85fbeb007a736125e8
      ingressClassResource:
        name: ingress-nginx
      metrics:
        serviceMonitor:
          enabled: true
        enabled: true

      # The number of replicas of the Ingress controller deployment.
      replicaCount: 2
      service:
        # The annotations of the Ingress Controller service.
        annotations:
          metallb.universe.tf/address-pool: default
          metallb.universe.tf/allow-shared-ip: SHARED-IP-02
        # The externalTrafficPolicy of the service. The value Local preserves the client source IP.
        externalTrafficPolicy: Cluster
