apiVersion: v1
kind: LimitRange
metadata:
  name: common-limit-range
spec:
  limits:
  - type: PersistentVolumeClaim
    max:
      storage: 50Gi # maximum storage request size
  - type: Container
    default: # define default limits
      cpu: "64"
      memory: 512Gi
    defaultRequest: # define default requests
      cpu: "0.1"
      memory: 100Mi
