apiVersion: v1
kind: LimitRange
metadata:
  name: common-limit-range
spec:
  limits:
  - type: PersistentVolumeClaim
    max:
      storage: "100Gi"
  - type: Container
    default: 
      cpu: 1
      memory: 1Gi
    defaultRequest:
      cpu: 0.1
      memory: 100Mi
