---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  releaseName: metrics-server
  valuesFrom:
  - kind: ConfigMap
    name: metrics-server-helm-chart-value-overrides # Align with the name of the ConfigMap containing all values
    valuesKey: values.yaml 
  chart:
    spec:
      chart: metrics-server
      version: '3.8.3'
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: kube-system
      # valuesFiles:
      #   - values.yaml
  interval: 5m
  suspend: false
  install:
    crds: Create
  upgrade:
    crds: CreateReplace # 