apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: flux-notifications
  namespace: flux-system
spec:
  providerRef:
    name: slack
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: '*'
    - kind: Kustomization
      name: '*'
  # https://github.com/fluxcd/kustomize-controller/issues/492#issuecomment-1195300509
  exclusionList:
    - "^Dependencies.*"
