apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: flux-notifications
  namespace: flux-system
spec:
  providerRef:
    name: slack
  eventSeverity: info # when the value is set to info, all events are forwarded to the alert provider API, including errors
  eventSources:
    - kind: GitRepository
      name: '*'
    - kind: Kustomization
      name: '*'
    - kind: HelmRepository
      name: '*'
    - kind: HelmChart
      name: '*'
    - kind: HelmRelease
      name: '*'
  # https://github.com/fluxcd/kustomize-controller/issues/492#issuecomment-1195300509
  exclusionList:
    - "^Dependencies.*"
