apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dex
  namespace: dex
spec:
  values:
    envVars:
    - name: GITHUB_CLIENT_ID
      valueFrom:
        secretKeyRef:
          name: github-client
          key: client-id
    - name: GITHUB_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: github-client
          key: client-secret
    config:
      # Set it to a valid URL
      issuer: https://dex.k8s-02.konturlabs.com

      # See https://dexidp.io/docs/storage/ for more options
      storage:
        type: memory

      staticClients:
      - name: 'Weave GitOps Core'
        id: weave-gitops
        secret: yYe26K2_QZj5JiougESejS68XoXXP
        redirectURIs:
        - 'https://localhost:9001/oauth2/callback'
        - 'https://0.0.0.0:9001/oauth2/callback'
        - 'http://0.0.0.0:9001/oauth2/callback'
        - 'http://localhost:4567/oauth2/callback'
        - 'https://localhost:4567/oauth2/callback'
        - 'http://localhost:3000/oauth2/callback'
        - 'https://flux.k8s-02.konturlabs.com/oauth2/callback'


      connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: $GITHUB_CLIENT_ID
          clientSecret: $GITHUB_CLIENT_SECRET
          redirectURI: https://dex.k8s-02.konturlabs.com/callback
          orgs:
          - name: fibednet 
            # teams:
            # - "Front-end developers OSS"


    ingress:
      hosts:
        - host: dex.k8s-02.konturlabs.com
          paths:
          - path: /
            pathType: ImplementationSpecific
      tls:
        - hosts:
          - dex.k8s-02.konturlabs.com
          secretName: dex-tls
