apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vmoperator
  namespace: monitoring
spec:
  chart:
    spec:
      chart: victoria-metrics-operator
      version: 0.28.0
  values:
    resources:
      limits:
        cpu: 100m
        memory: 300Mi
      requests:
        cpu: 50m
        memory: 100Mi
