apiVersion: operator.victoriametrics.com/v1beta1
kind: VMCluster
metadata:
  name: vmcluster-persistent
spec:
  retentionPeriod: "1"
  replicationFactor: 1     
  vmstorage:
    replicaCount: 1
    storageDataPath: "/vm-data"
    podMetadata:
      labels:
        owner: infra
    storage:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 5Gi
    resources:
      requests:
        cpu: "100m"
        memory: "100Mi"
      limits:
        cpu: "2"
        memory: 2048Mi
  vmselect:
    replicaCount: 1
    cacheMountPath: "/select-cache"
    podMetadata:
      labels:
        owner: infra
    storage:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 2Gi
    resources:
      requests:
        cpu: "100m"
        memory: "100Mi"
      limits:
        cpu: "1"
        memory: "500Mi"
  vminsert:
    replicaCount: 1
    podMetadata:
      labels:
        owner: infra
    resources:
      requests:
        cpu: "100m"
        memory: "100Mi"
      limits:
        cpu: "1"
        memory: "500Mi"
