apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/limit-range

namespace: dev-osrm

patchesJson6902:
  - target:
      kind: LimitRange
      name: common-limit-range
      version: v1
    patch: |-
      - op: replace
        path: /spec/limits/0/max/storage
        value: "500Gi"
