# # https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#monitoring.coreos.com/v1.Probe
# apiVersion: monitoring.coreos.com/v1
# kind: Probe
# metadata:
#   name: dev-blackbox-exporter-post
#   namespace: monitoring
# spec:
#   jobName: dev-https-post-endpoints
#   interval: 120s
#   module: http_2xx
#   prober:
#     url: blackbox-exporter.monitoring.svc.cluster.local:19115
#     scheme: http
#     path: /probe
#   method: POST
#   targets:
#     staticConfig:
#       static:
#         - "https://test-apps-ninja02.konturlabs.com/active/about?app=58851b50-9574-4aec-a3a6-425fa18dcb54&feed=kontur-public&layers=BIV__Kontur+OpenStreetMap+Quantity%2CactiveContributors%2CeventShape%2CKLA__hotProjects_outlines%2Cfocused-geometry"

