apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: blackbox-exporter
  namespace: monitoring
spec:
  jobName: https-get-dn
  interval: 60s
  module: http_2xx
  prober:
    url: blackbox-exporter.monitoring.svc.cluster.local:19115
    scheme: http
    path: /probe
  targets:
    staticConfig:
      static: [https://disaster.ninja/active]
