# https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#monitoring.coreos.com/v1.Probe
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: test-post-custom
  namespace: monitoring
spec:
  jobName: test-post-custom
  interval: 120s
  module: http_post_custom
  prober:
    url: blackbox-exporter.monitoring.svc.cluster.local:19115
    scheme: http
    path: /probe
  targets:
    staticConfig:
      static:
        - "https://test-apps02.konturlabs.com/insights-api/graphql"

