apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Define sources first
  - ../../sources
  # Define namespaces then
  - ./namespaces
  # Define deployed applications
  - ../../base/victoriametrics-operator
  - ../../base/local-path-provisioner
  - ../../base/calico
#  - ../../base/nginx-ingress
  - ../../base/ingress-nginx-custom
  - ../../base/cert-manager-crds
  - ../../base/metallb
  - ../../base/metrics-server
  - ../../base/tigera-operator
  - ../../base/kube-prometheus-operator
  - ../../base/local-path-provisioner-regular
  - ../../base/local-path-provisioner-fast
  - ../../base/postgres-operator
  - ./resource-quota
  - ./limit-range

patchesStrategicMerge:
  - victoriametrics-operator/release.yaml
  - local-path-provisioner/configmap.yaml
  - local-path-provisioner/deployment.yaml
#  - nginx-ingress/release.yaml
  - ingress-nginx-custom/release.yaml
  - metallb/release.yaml
  - tigera-operator/release.yaml
  - kube-prometheus-operator/prometheus-operator-deployment.yaml
  - local-path-provisioner-regular/configmap.yaml
  - local-path-provisioner-regular/deployment.yaml
  - local-path-provisioner-regular/storageclass.yaml
  - local-path-provisioner-fast/configmap.yaml
  - local-path-provisioner-fast/deployment.yaml
