apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Define sources first
  - ../../sources
  # Define namespaces then
  - ./namespaces
  # Define deployed applications
  - ../../base/victoriametrics-operator
  - ../../base/local-path-provisioner
  - ../../base/calico
  - ../../base/nginx-ingress
patchesStrategicMerge:
  - victoriametrics-operator/release.yaml
  - local-path-provisioner/configmap.yaml
  - local-path-provisioner/deployment.yaml
  - nginx-ingress/release.yaml
