# Despite that we specify namespace as default, resources will be installed in calico-system and tigera-operator namespaces
# they are hardcoded https://projectcalico.docs.tigera.io/archive/v3.21/getting-started/kubernetes/helm
# Also helm release created in default namespace because originally it was created manually in default namespace

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: calico
  namespace: default
spec:
  chart:
    spec:
      chart: tigera-operator
      version: 3.27.0
  values:
    installation:
      calicoNetwork:
        nodeAddressAutodetectionV4:
          canReach: 10.217.128.10
