# Despite that we specify namespace as default, resources will be installed in calico-system and tigera-operator namespaces
# they are hardcoded https://docs.tigera.io/calico/3.28/getting-started/kubernetes/helm

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: calico
  namespace: tigera-operator
spec:
  chart:
    spec:
      chart: tigera-operator
      version: 3.28.3
  values:
    installation:
      calicoNetwork:
        nodeAddressAutodetectionV4:
          canReach: 10.217.128.10
