# https://docs.tigera.io/calico/3.28/getting-started/kubernetes/helm
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: calico
  namespace: tigera-operator
spec:
  chart:
    spec:
      chart: tigera-operator
      version: 3.28.3
      sourceRef:
        kind: HelmRepository
        name: projectcalico
        namespace: flux-system
  interval: 10m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace # Create new CRDs, update (replace) existing ones, but do not delete CRDs which no longer exist in the current helm release.
