apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: default
  namespace: default
spec:
  suspend: false
  chart:
    spec:
      chart: nginx-ingress
      version: 0.15.0
      sourceRef:
        kind: HelmRepository
        name: nginx-ingress
        namespace: flux-system
  interval: 10m
  values:
    controller:
      # The number of replicas of the Ingress controller deployment.
      replicaCount: 1
