apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: default
  namespace: default
spec:
  suspend: false
  chart:
    spec:
      chart: nginx-ingress
      version: 0.15.0
  values:
# Enable custom NGINX configuration snippets in Ingress, VirtualServer, VirtualServerRoute and TransportServer resources.
    controller.enableSnippets: true
    annotations:
      metallb.universe.tf/address-pool: default
      metallb.universe.tf/allow-shared-ip: SHARED-IP-01
