apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: default
  namespace: default
spec:
  chart:
    spec:
      version: 0.15.2
  values:
    image:
      repository: 'nexus.kontur.io:8084/konturdev/nginx-ingress'
      tag: 2.4.2-kontur-mainline
