apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: default
  namespace: default
spec:
  suspend: false
  chart:
    spec:
      chart: nginx-ingress
      version: 0.15.0
  values:
    controller:
      # Enable custom NGINX configuration snippets in Ingress, VirtualServer, VirtualServerRoute and TransportServer resources.
      enableSnippets: true
      # The number of replicas of the Ingress controller deployment.
      replicaCount: 2

      service:
        # The annotations of the Ingress Controller service.
        annotations:
          metallb.universe.tf/address-pool: default
          metallb.universe.tf/allow-shared-ip: SHARED-IP-01
