apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled

---
apiVersion: v1
kind: Namespace
metadata:
  name: local-path-storage
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled

---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled

---
apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled

---
apiVersion: v1
kind: Namespace
metadata:
  name: postgres-operator
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
