apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: cluster-node-condition-rules
  namespace: monitoring
spec:
  groups:
    - name: ClusterNodeConditions
      rules:
        - alert: NodeConditionNotReady
          annotations:
            message: '{{ $labels.node }} condition is {{ $labels.condition }}'
            summary: Node condition is not Ready which means it's one of MemoryPressure, DiskPressure, PIDPressure, NetworkUnavailable
          expr: |
            max_over_time(kube_node_status_condition{condition!="Ready", status="true"}[5m])
            >= 1
          for: 1m
          labels:
            severity: critical
            target: OnCall

    - name: ClusterNodeResourceUsage
      rules:
        - alert: AllocatableAmountOfNodeResourcesIsLessThanThreshold
          annotations:
            message: '[TESTING - PLEASE IGNORE] {{ $labels.node }} {{ $labels.resource }} allocatable percentage is {{ $value }}'
            summary: Allocatable amount of resources on a node is lower than threshold
          expr: |
            min_over_time(kube_node_status_allocatable{resource=~"cpu|ephemeral_storage|memory"}[5m]) / kube_node_status_capacity{resource=~"cpu|ephemeral_storage|memory"}
            <= 0.5
          for: 1m
          labels:
            severity: warning
            target: OnCall
