apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: cluster-node-condition-rules
  namespace: monitoring
spec:
  groups:
    - name: PodEvictions
      rules:
        - alert: PodEvictionsDuringLastMinute
          annotations:
            message: '{{ $value }} pod evictions happened on {{ $labels.node }} due to {{ $labels.eviction_signal }} eviction signal'
            summary: Pod evictions happened
          expr: |
            increase(kubelet_evictions[1m])
            > 0
          for: 1m
          labels:
            severity: critical
