apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ww-gitops
  namespace: flux-system
spec:
  chart:
    spec:
      chart: weave-gitops
      version: v4.0.0
      sourceRef:
        kind: HelmRepository
        name: ww-gitops
  interval: 1m0s
  values:
    logLevel: info
    adminUser:
      create: true
      username: weave-gitops
      passwordHash: "$2a$10$9JjCtcenwbHAFCqBeyWVie.Cp6ELindFNryBtotfv8C3ythlRi2u."
    ingress:
      hosts:
      - host: flux.k8s-01.konturlabs.com
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "ww-gitops-weave-gitops"
                port:
                  number: 9001
      tls:
      - hosts:
        - flux.k8s-01.konturlabs.com
        secretName: flux-ui-tls