apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: minio-operator
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: https://operator.min.io

---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: operator
  namespace: minio-operator
spec:
  chart:
    spec:
      chart: operator
      version: 5.0.14
      sourceRef:
        kind: HelmRepository
        name: minio-operator
        namespace: flux-system
