apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio-operator
  namespace: minio-operator
spec:
  chart:
    spec:
      chart: operator
      version: 5.0.14
      sourceRef:
        kind: HelmRepository
        name: minio-operator
        namespace: flux-system
