apiVersion: operator.victoriametrics.com/v1beta1
kind: VMCluster
metadata:
  name: vmcluster-persistent
  namespace: monitoring
spec:
  retentionPeriod: "6"
  replicationFactor: 2   
  vmstorage:
    replicaCount: 3
    # https://github.com/VictoriaMetrics/VictoriaMetrics/issues/86
    extraArgs:
      dedup.minScrapeInterval: 5s
    affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: "app.kubernetes.io/name"
                operator: In
                values:
                - "victoriametrics"
            topologyKey: "kubernetes.io/hostname"
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          resources:
            requests:
              storage: 20Gi
    resources:
      requests:
        cpu: "100m"
        memory: "500Mi"
      limits:
        cpu: "2"
        memory: 2048Mi
  vmselect:
    replicaCount: 2
    # https://github.com/VictoriaMetrics/VictoriaMetrics/issues/86
    extraArgs:
      dedup.minScrapeInterval: 1ms
    affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: "app.kubernetes.io/name"
                operator: In
                values:
                - "victoriametrics"
            topologyKey: "kubernetes.io/hostname"
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          resources:
            requests:
              storage: 2Gi
    resources:
      requests:
        cpu: "100m"
        memory: "200Mi"
      limits:
        cpu: "1"
        memory: "500Mi"
  vminsert:
    replicaCount: 2
    affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: "app.kubernetes.io/name"
                operator: In
                values:
                - "victoriametrics"
            topologyKey: "kubernetes.io/hostname"
    resources:
      requests:
        cpu: "100m"
        memory: "200Mi"
      limits:
        cpu: "1"
        memory: "500Mi"
