apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Define sources first
  - ../../sources
  # Define namespaces then
  - ./namespaces
  # Define deployed applications
  - ../../base/victoriametrics-operator
  - ../../base/kube-prometheus-operator
patchesStrategicMerge:
  - victoriametrics-operator/release.yaml
  - kube-prometheus-operator/prometheus-operator-deployment.yaml
