apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-path-provisioner
  namespace: local-path-storage
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: local-path-provisioner
          image: rancher/local-path-provisioner:v0.0.22
