apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/vmcluster
  - ../../base/kube-prometheus
  - ../../base/postgres-exporter
  - ../../base/fluentbit
  - ../../base/flux
  - flux/podmonitor.yaml
patchesStrategicMerge:
  - vmcluster/vmcluster-crd.yaml
  - flux/alerts.yaml
