apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/vmcluster
  - ../../base/kube-prometheus
  - ../../base/postgres-exporter
patchesStrategicMerge:
  - vmcluster/vmcluster-crd.yaml
