apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/vmcluster
  - ../../base/kube-prometheus
  - ../../base/postgres-exporter
  - ../../base/fluentbit
  - ../../base/flux
  #- ../../base/weave-gitops
  - ../../base/cert-manager
  - flux/podmonitor.yaml
patchesStrategicMerge:
  - vmcluster/vmcluster-crd.yaml
  - flux/alerts.yaml
  #- weave-gitops/release.yaml
  - cert-manager/cluster_issuer_letsencrypt_prod.yaml
  - cert-manager/cluster_issuer_letsencrypt_stage.yaml
