apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/instance: k8s
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 2.34.0
  name: k8s
  namespace: monitoring
spec:
  remoteWrite:
    - url: http://vminsert-vmcluster-persistent.monitoring.svc.cluster.local:8480/insert/0/prometheus/api/v1/write
  # https://github.com/VictoriaMetrics/VictoriaMetrics/issues/86
  replicaExternalLabelName: ""
  externalLabels:
    cluster: "k8s-01"
  image: quay.io/prometheus/prometheus:v2.34.0
  replicas: 2
  resources:
    requests:
      memory: 400Mi
  version: 2.34.0
