apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - alertmanager-alertmanager.yaml
  - alertmanager-ingress.yaml
  - alertmanager-podDisruptionBudget.yaml
  - alertmanager-prometheusRule.yaml
  - alertmanager-secret.yaml
  - alertmanager-service.yaml
  - alertmanager-serviceAccount.yaml
  - alertmanager-serviceMonitor.yaml
