apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-path-provisioner-fast
spec:
  replicas: 1
  selector:
    matchLabels:
      app: local-path-provisioner-fast
  template:
    metadata:
      labels:
        app: local-path-provisioner-fast
    spec:
      serviceAccountName: local-path-provisioner-service-account-fast
      containers:
        - name: local-path-provisioner
          image: rancher/local-path-provisioner:v0.0.23
          imagePullPolicy: IfNotPresent
          command:
            - local-path-provisioner
            - --debug
            - start
            - --config
            - /etc/config/config.json
            - --provisioner-name
            - local-path-fast
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config/
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      volumes:
        - name: config-volume
          configMap:
            name: local-path-config-fast
