apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: core-apps
  namespace: flux-system
spec:
  force: true # recreate resources on immutable fields changes
  interval: 10m0s # detect drift and undo kubectl edits every hour
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./core-apps/clusters/k8s-01
  prune: true # remove stale resources from cluster
  # Disable Health assessment
  # https://fluxcd.io/flux/components/kustomize/kustomization/#health-assessment
  # https://fluxcd.io/flux/components/kustomize/kustomization/#status
  wait: false # wait for all applied resources to become ready
  # timeout: 3m0s # give up waiting after three minutes
  retryInterval: 2m0s # retry every two minutes on apply or waiting failures
