---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: kontur-platform
  namespace: flux-system
spec:
  suspend: false
  interval: 5m0s
  ref:
    branch: 11715-setup-flux-repo-for-kontur-business-applications #TODO set to main
  secretRef:
    name: disaster-ninja-cd
  url: ssh://git@gitlab.com/kontur-private/platform/disaster-ninja-cd.git #TODO move to a separate repo / rename?
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kontur-platform
  namespace: flux-system
spec:
  force: true # recreate resources on immutable fields changes
  interval: 10m0s # detect drift and undo kubectl edits every 10 minutes
  sourceRef:
    kind: GitRepository
    name: kontur-platform
    namespace: flux-system
  path: ./flux/clusters/k8s-01
  prune: true # remove stale resources from cluster
  wait: true # wait for all applied resources to become ready
  timeout: 3m0s # give up waiting after three minutes
  retryInterval: 2m0s # retry every two minutes on apply or waiting failures
