apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ww-gitops
  namespace: flux-system
spec:
  values:
    logLevel: info
    adminUser:
      create: true
      username: weave-gitops
      passwordHash: "$2a$10$YEPsU.FmvQlG0vkD2FjUN.OMWZmOIcX3WTJFidI/HSPobwjupARbe"
    ingress:
      hosts:
      - host: flux.k8s-02.konturlabs.com
        http:
          paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ww-gitops-weave-gitops
                port:
                  number: 9001
      tls:
      - hosts:
        - flux.k8s-02.konturlabs.com
        secretName: flux-ui-tls
