apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ww-gitops
  namespace: flux-system
spec:
  chart:
    spec:
      chart: weave-gitops
      version: v4.0.0
      sourceRef:
        kind: HelmRepository
        name: ww-gitops
  interval: 1m0s
  values:
    logLevel: info
    ingress:
      hosts:
      - host: flux.k8s-01.konturlabs.com
        http:
          paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ww-gitops-weave-gitops
                port:
                  number: 9001
      tls:
      - hosts:
        - flux.k8s-01.konturlabs.com
        secretName: flux-ui-tls
