apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nvdp
  namespace: nvidia-device-plugin
spec:
  releaseName: nvdp
  valuesFrom:
    - kind: ConfigMap
      name: nvdp-configmap
      valuesKey: configmap-values.yaml
  chart:
    spec:
      chart: nvidia-device-plugin
      reconcileStrategy: ChartVersion
      version: 0.17.2
      sourceRef:
        kind: HelmRepository
        name: nvdp
        namespace: flux-system
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  interval: 30m
  suspend: false
