apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ww-gitops
  namespace: flux-system
spec:
  chart:
    spec:
      chart: weave-gitops
      version: v4.0.0
      sourceRef:
        kind: HelmRepository
        name: ww-gitops
  interval: 10m
  values:
    logLevel: info
    rbac:
      create: true
    ingress:
      enabled: true
      className: "nginx"
      annotations:
        acme.cert-manager.io/http01-edit-in-place: "true"
        cert-manager.io/cluster-issuer: letsencrypt-production
