apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: default
  namespace: default
spec:
  chart:
    spec:
      chart: nginx-ingress
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: nginx-ingress
        namespace: flux-system
      version: 0.15.2
  install:
    crds: Create
  interval: 10m
  suspend: false
  upgrade:
    # Create new CRDs, update (replace) existing ones, but do not delete CRDs which no longer exist in the current helm release.
    crds: CreateReplace
  values:
    controller:
      config:
        entries:
          http-snippets: |
            include CORS_01_http.inc.conf;
          main-snippets: |
            pcre_jit on;
            load_module /usr/lib/nginx/modules/ngx_http_headers_more_filter_module.so;
            load_module /usr/lib/nginx/modules/ngx_http_js_module.so;
      # Enable custom NGINX configuration snippets in Ingress, VirtualServer, VirtualServerRoute and TransportServer resources.
      enableSnippets: true
      image:
        repository: 'nexus.kontur.io:8084/konturdev/nginx-ingress'
        tag: 2.4.3-kontur-mainline
      # The Ingress Controller processes all the resources that do not have the "ingressClassName" field for all versions of kubernetes.
      ingressClass: nginx
      # The number of replicas of the Ingress controller deployment.
      replicaCount: 2
      service:
        # The annotations of the Ingress Controller service.
        annotations:
          metallb.universe.tf/address-pool: default
          metallb.universe.tf/allow-shared-ip: SHARED-IP-01
        # The externalTrafficPolicy of the service. The value Local preserves the client source IP.
        externalTrafficPolicy: Cluster
      # New Ingresses without an ingressClassName field specified will be assigned the class specified in `controller.ingressClass`.
      setAsDefaultIngress: true
