apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled

---
apiVersion: v1
kind: Namespace
metadata:
  name: dev-raster-tiler
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled

---
apiVersion: v1
kind: Namespace
metadata:
  name: test-raster-tiler
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled

---
apiVersion: v1
kind: Namespace
metadata:
  name: prod-raster-tiler
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled

---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled

---
apiVersion: v1
kind: Namespace
metadata:
  name: postgres-operator
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled

---
apiVersion: v1
kind: Namespace
metadata:
  name: minio-operator
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
