apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  annotations:
    kustomize.toolkit.fluxcd.io/reconcile: disabled
spec:
  acme:
    email: root+k8s-01-staging@kontur.io
