apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
  annotations:
    kustomize.toolkit.fluxcd.io/reconcile: disabled
spec:
  suspend: true
  chart:
    spec:
      chart: cert-manager
      version: v1.6.3
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  interval: 10m
  values:
    logLevel: 6
