apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: fluentbit
spec:
  groups:
    - name: FluentBitOutputErrors
      rules:
        - alert: FluentBitOutputError
          annotations:
            message: 'Number of FluentBit output errors during last 3 minutes is {{ $value }}'
            summary: Number of FluentBit output errors during last 3 minutes
          expr: |
            sum(sum_over_time(fluentbit_output_errors_total[3m]))
            > 0
          for: 5m
          labels:
            severity: warning
        - alert: FluentBitNoOutputBytesProcessed
          expr: rate(fluentbit_output_proc_bytes_total[5m]) == 0
          annotations:
            message: |
              Fluent Bit instance {{ $labels.instance }}'s output plugin {{ $labels.name }} has not processed any
              bytes for at least 15 minutes.
            summary: No Output Bytes Processed
          for: 15m
          labels:
            severity: warning
