apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit
  labels:
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/version: 1.9.3
data:
  custom_parsers.conf: |
    [PARSER]
        Name docker_no_time
        Format json
        Time_Keep Off
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L

    [PARSER]
        Name kontur_json_parser
        Format json
        Time_Key timestamp
        Time_Format %Y-%m-%dT%H:%M:%S.%f %z

    [MULTILINE_PARSER]
        Name multiline_psql
        Type regex
        Flush_timeout 1000
        Key_content log
        # Regex rules for multiline parsing
        # ---------------------------------
        # configuration hints:
        #  - first state always has the name: start_state
        #  - every field in the rule must be inside double quotes
        #
        # rules   |   state name   | regex pattern                   | next state name
        # --------|----------------|--------------------------------------------------
        rule         "start_state"   "(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}.\d{3})(.*)"  "cont"
        rule         "cont"          "^([^0-9]{4}|[ \t]+)(.*)$"                     "cont"

  fluent-bit.conf: |
    [SERVICE]
        Daemon Off
        Flush 1
        Log_Level info
        Parsers_File parsers.conf
        Parsers_File custom_parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port 2020
        Health_Check On

    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        Exclude_Path /var/log/containers/test-(raster-tiler|tiler)*.log
        multiline.parser docker, cri
        Tag kube.*
        Mem_Buf_Limit 20MB
        Skip_Long_Lines On
        Buffer_Chunk_Size 512KB
        Buffer_Max_Size 2MB

    [INPUT]
        Name tail
        Path /var/log/postgres/*.log
        multiline.parser multiline_psql
        Skip_Empty_Lines On
        Tag postgres.*
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On

    [INPUT]
        Name systemd
        Tag host.*
        Path /run/log/journal
        Systemd_Filter _SYSTEMD_UNIT=kubelet.service
        Read_From_Tail On

    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log On
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On
        Buffer_Size 256KB

    [FILTER]
        Name Modify
        Match postgres.*
        Add nodename ${NODE_NAME}

    [FILTER]
        Name record_modifier
        Match *
        Remove_key output*

    [OUTPUT]
        Name es
        Match *
        Host ${FLUENT_ELASTICSEARCH_HOST}
        Port ${FLUENT_ELASTICSEARCH_PORT}
        HTTP_User ${FLUENT_ELASTICSEARCH_USER}
        HTTP_Passwd ${FLUENT_ELASTICSEARCH_PASSWORD}
        Logstash_Format Off
        Retry_Limit False
        tls On
        Suppress_Type_Name On
        # Trace_Output On
        Trace_Error On
        Replace_Dots On
        Include_Tag_Key true
        Tag_Key tags
        Index logstash
        Workers 1
