apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Define sources first
  - ../../sources
  # Define namespaces then
  - ./namespaces
  # Define deployed applications
  - ../../base/victoriametrics-operator
  - ../../base/kube-prometheus-operator
  - ../../base/local-path-provisioner
  - ../../base/calico
  - ../../base/nginx-ingress
  - ../../base/metallb
  - ../../base/cert-manager-crds
patchesStrategicMerge:
  - victoriametrics-operator/release.yaml
  - kube-prometheus-operator/prometheus-operator-deployment.yaml
  - local-path-provisioner/configmap.yaml
  - local-path-provisioner/deployment.yaml
  - metallb/release.yaml
  - nginx-ingress/release.yaml
