apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: postgres-operator
spec:
  force: false
  healthChecks:
  - apiVersion: apps/v1
    kind: Deployment
    name: pgo
    namespace: postgres-operator
  interval: 30m
  path: ./kustomize/install/default
  prune: true
  sourceRef:
    kind: GitRepository
    name: pgo-kustomize-installer
    namespace: flux-system
  timeout: 2m
