apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana02-kontur-io
  namespace: monitoring
spec:
  rules:
    - host: grafana02.kontur.io
  tls:
    - hosts:
        - grafana02.kontur.io
      secretName: grafana02-kontur-io-tls
