apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 9.3.16
    prometheus: k8s
    role: alert-rules
  name: grafana-rules
  namespace: monitoring
spec:
  groups:
  - name: grafana_rules
    rules:
    - expr: |
        sum by (namespace, job, handler, status_code) (rate(grafana_http_request_duration_seconds_count[5m]))
      record: namespace_job_handler_statuscode:grafana_http_request_duration_seconds_count:rate5m
  - name: GrafanaAlerts
    rules:
    - alert: GrafanaRequestsFailing
      annotations:
        message: '{{ $labels.namespace }}/{{ $labels.job }}/{{ $labels.handler }} is experiencing {{ $value | humanize }}% errors'
        runbook_url: https://runbooks.prometheus-operator.dev/runbooks/grafana/grafanarequestsfailing
      expr: |
        100 * namespace_job_handler_statuscode:grafana_http_request_duration_seconds_count:rate5m{handler!~"/api/datasources/proxy/:id.*|/api/ds/query|/api/tsdb/query", status_code=~"5.."}
        / ignoring (status_code)
        sum without (status_code) (namespace_job_handler_statuscode:grafana_http_request_duration_seconds_count:rate5m{handler!~"/api/datasources/proxy/:id.*|/api/ds/query|/api/tsdb/query"})
        > 50
      for: 5m
      labels:
        severity: warning

    - alert: GrafanaRequestsErrors
      annotations:
        summary: Grafana Errors rate is too high
        description: |
          Grafana https://grafana02.kontur.io requests error rate {{ $value | humanize }}% is too high

          Recommended action:
          * Open the Grafana dashboard - https://grafana02.kontur.io/d/6be0s85Mk/grafana-overview
          * Follow runbook - https://TODO
        runbook_url: https://TODO
      expr: |
        (sum(rate(grafana_http_request_duration_seconds_count{status_code=~"[45].."}[5m]))
        /
        sum(rate(grafana_http_request_duration_seconds_count{}[5m]))*100)
        > 90
      for: 5m
      labels:
        severity: warning

    - alert: GrafanaRequestsDuration
      annotations:
        summary: Grafana requests duration is too high
        description: |
          Grafana https://grafana02.kontur.io requests duration {{ printf "%.3g" $value }}ms is too high

          Recommended action:
          * Open the Grafana dashboard - https://grafana02.kontur.io/d/6be0s85Mk/grafana-overview
          * Follow runbook - https://TODO
        runbook_url: https://TODO
      expr: |
        histogram_quantile(0.99, sum(rate(grafana_http_request_duration_seconds_bucket{}[5m])) by (le))
        > 100
      for: 5m
      labels:
        severity: warning
